//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHLDDK
    {
        public int IDBHLDDK { get; set; }
        public Nullable<int> DBDKID { get; set; }
        public Nullable<int> BHLDID { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Size { get; set; }
    
        public virtual DinhBienDK DinhBienDK { get; set; }
    }
}
