//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardNhanVien
    {
        public int ID { get; set; }
        public Nullable<int> NhanVienNTID { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string MSCard { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public Nullable<bool> TTThe { get; set; }
    
        public virtual NhanVienNT NhanVienNT { get; set; }
    }
}
