//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhPheDuyet
    {
        public int ID { get; set; }
        public string LoaiHS { get; set; }
        public Nullable<bool> C1 { get; set; }
        public Nullable<bool> C2 { get; set; }
        public Nullable<bool> C3 { get; set; }
        public Nullable<bool> C4 { get; set; }
        public Nullable<bool> C5 { get; set; }
    }
}
