//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyHAT
    {
        public int IDDKHAT { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public string ChiHuyTruong { get; set; }
        public System.DateTime NgayDuKienHoc { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public int NguoiDungID { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NhaThau NhaThau { get; set; }
    }
}
