//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachHAT
    {
        public int ID { get; set; }
        public Nullable<int> DKHATID { get; set; }
        public string CMND { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string QuocTich { get; set; }
        public string ChucVu { get; set; }
        public Nullable<System.DateTime> ThoiHanThe { get; set; }
    }
}
