//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhBienDK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DinhBienDK()
        {
            this.BHLDDKs = new HashSet<BHLDDK>();
            this.PheDuyetBHLDs = new HashSet<PheDuyetBHLD>();
        }
    
        public int IDDBDK { get; set; }
        public Nullable<int> NhanSuID { get; set; }
        public Nullable<int> DBID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> VTLVID { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> TinhTrangID { get; set; }
        public Nullable<int> PheDuyetID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BHLDDK> BHLDDKs { get; set; }
        public virtual DinhBienBHLD DinhBienBHLD { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PheDuyetBHLD> PheDuyetBHLDs { get; set; }
    }
}
