//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhBienChiTiet
    {
        public int IDDBCT { get; set; }
        public Nullable<int> BHLDID { get; set; }
        public Nullable<int> DBID { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThoiHan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DinhBienBHLD DinhBienBHLD { get; set; }
        public virtual LoaiBHLD LoaiBHLD { get; set; }
    }
}
