//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhBienTH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DinhBienTH()
        {
            this.BHLDTHs = new HashSet<BHLDTH>();
            this.PheDuyetTHs = new HashSet<PheDuyetTH>();
        }
    
        public int IDDBTH { get; set; }
        public Nullable<int> NhanSuID { get; set; }
        public Nullable<int> DBTHID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> VTLVID { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> TinhTrangID { get; set; }
        public Nullable<int> PheDuyetID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BHLDTH> BHLDTHs { get; set; }
        public virtual DinhBienBHLDTH DinhBienBHLDTH { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PheDuyetTH> PheDuyetTHs { get; set; }
    }
}
