//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaHanHD
    {
        public int IDGHHD { get; set; }
        public Nullable<int> HDID { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
