//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeQuaHoc
    {
        public int IDKQHAT { get; set; }
        public Nullable<int> NhanVienNTID { get; set; }
        public Nullable<int> HDID { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public Nullable<System.DateTime> NgayHoc { get; set; }
        public Nullable<bool> KetQua { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NhanVienNT NhanVienNT { get; set; }
        public virtual NhaThau NhaThau { get; set; }
    }
}
