//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiBHLD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiBHLD()
        {
            this.DinhBienBHLDTHCTs = new HashSet<DinhBienBHLDTHCT>();
            this.DinhBienChiTiets = new HashSet<DinhBienChiTiet>();
            this.ThuHoiBHLDCTs = new HashSet<ThuHoiBHLDCT>();
        }
    
        public int IDBHLD { get; set; }
        public string TenBHLD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhBienBHLDTHCT> DinhBienBHLDTHCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhBienChiTiet> DinhBienChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuHoiBHLDCT> ThuHoiBHLDCTs { get; set; }
    }
}
