//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiViec
    {
        public int IDNV { get; set; }
        public Nullable<int> NhanSuID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> VTLVID { get; set; }
        public Nullable<System.DateTime> NgayNV { get; set; }
        public string GhiChu { get; set; }
    }
}
