//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.DinhBienDKs = new HashSet<DinhBienDK>();
            this.DinhBienNVs = new HashSet<DinhBienNV>();
            this.DinhBienTHs = new HashSet<DinhBienTH>();
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int ID { get; set; }
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string HoTenKhongDau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDTinhTrangLV { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public string CMND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhBienDK> DinhBienDKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhBienNV> DinhBienNVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhBienTH> DinhBienTHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TinhTrangLV TinhTrangLV { get; set; }
        public virtual Vitri Vitri { get; set; }
    }
}
