//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PheDuyet
    {
        public int ID { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<int> LoaiHSID { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public Nullable<int> HoSoID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
    }
}
