//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PheDuyetBHLD
    {
        public int IDPD { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<int> LoaiHSID { get; set; }
        public Nullable<int> DBBHLDID { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> CapPD { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DinhBienDK DinhBienDK { get; set; }
    }
}
