//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBANCHN_VIEW
    {
        public int IDPhongBan { get; set; }
        public string TenVT { get; set; }
        public string TenDai { get; set; }
    }
}
