//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiHanBHLDDKCT
    {
        public int IDTHDDKCT { get; set; }
        public Nullable<int> THDKID { get; set; }
        public Nullable<int> BHLDID { get; set; }
        public Nullable<int> ThoiHan { get; set; }
        public Nullable<System.DateTime> NgayNV { get; set; }
    }
}
