//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongQuan
    {
        public int IDTongquan { get; set; }
        public string VBCuatoi { get; set; }
        public string VBChoky { get; set; }
        public string VBChuyendi { get; set; }
        public string VBChuadoc { get; set; }
        public Nullable<int> NhanvienID { get; set; }
    }
}
