//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int ID { get; set; }
        public string NoiDungVB { get; set; }
        public string DoKhan { get; set; }
        public string HinhThucVB { get; set; }
        public string NguoiKy { get; set; }
        public string TinhTrangXL { get; set; }
        public string DonViTK { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string File { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
