//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHATHAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int ID { get; set; }
        public Nullable<int> NhanVienNTID { get; set; }
        public Nullable<int> NhaThauID { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public string NoiDungVP { get; set; }
        public Nullable<System.DateTime> NgayVP { get; set; }
        public Nullable<int> MucVP { get; set; }
        public Nullable<int> TSVP { get; set; }
        public Nullable<bool> TtThe { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NhanVienNT NhanVienNT { get; set; }
        public virtual NhaThau NhaThau { get; set; }
    }
}
